# Generated by Django 4.0.6 on 2022-07-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False),
        ),
    ]
