# Generated by Django 4.0.6 on 2022-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_producto_id_producto_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1000, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
