# Generated by Django 4.0.6 on 2022-07-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_producto_producto_id_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default=1, upload_to='', verbose_name='images'),
            preserve_default=False,
        ),
    ]
